spring.application.name=backend
# Puerto del servidor
server.port=${PORT:8080}

# Conexión a PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/LaSerranitaDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}

# Configuraci\u00f3n de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuraci\u00f3n SMTP para env\u00edo de correos
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:fincakichuay@gmail.com}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Tamaño máximo de archivos (para Base64 largo)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB
server.tomcat.max-http-form-post-size=10MB

# Directorio de subida de imágenes
upload.path=./uploads/
gemini.api.key=AQ.Ab8RN6LEHSZ9YgnRhIjQUrDILw5DybN58HISb4xThKwQ11zKlg

