spring.application.name=backend
# Puerto del servidor
server.port=8080

# Conexi\u00f3n a PostgreSQL (OJO: El puerto por defecto de Postgres es 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/LaSerranitaDB
spring.datasource.username=postgres
spring.datasource.password=12345

# Configuraci\u00f3n de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuraci\u00f3n SMTP para env\u00edo de correos (reemplazar con credenciales reales)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fincakichuay@gmail.com
spring.mail.password=guoi mmjx jpkb sain
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OpenAI Configuration
openai.api.key=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
openai.api.url=https://api.openai.com/v1/chat/completions